Q:

Issues with cv_bridge when using cameracalibrator.py in Indigo

After updating to Ubuntu 14.04 and Indigo I'm not able to execute the camera_calibration.
With last version of opencv libraries (github repository master) python keeps looking for "cv.so". I have no issues with Hydro.
Also when using the repository installation of opencv (2.4.9) camera_calibration gives me this error:
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/ros/indigo/lib/camera_calibration/cameracalibrator.py", line 68, in run
    self.function(m)
  File "/opt/ros/indigo/lib/camera_calibration/cameracalibrator.py", line 138, in handle_monocular
    drawable = self.c.handle_msg(msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 749, in handle_msg
    gray = self.mkgray(msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 262, in mkgray
    mono16 = self.br.imgmsg_to_cv(msg, "mono16")
AttributeError: CvBridge instance has no attribute 'imgmsg_to_cv'

I am trying to calibrate an Argos 3D Tof camera. Everything works in Hydro. Even when I try to execute:
rosrun camera_calibration cameracalibrator.py

I do not get any answer. It gets frozen.
I have not seem any bug reported with the same problem. Is someone else having this issue?

Originally posted by amerino on ROS Answers with karma: 13 on 2014-05-28
Post score: 0

Original comments
Comment by DrBot on 2014-07-04:
I see the following on indigo ubuntu 14.04 AMD 64:
[ERROR] [WallTime: 1404511515.772882] bad callback: <bound method FaceDetector.image_callback of <main.FaceDetector object at 0x7f8665897e10>>
Traceback (most recent call last):
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 688, in _invoke_callback
cb(msg)
File "/home/alan/catkin_ws/src/rbx1/rbx1_vision/src/rbx1_vision/ros2opencv2.py", line 140, in image_callback
frame = self.convert_image(data)
File "/home/alan/catkin_ws/src/rbx1/rbx1_vision/src/rbx1_vision/ros2opencv2.py", line 281, in convert_image
cv_image = self.bridge.imgmsg_to_cv(ros_image, "bgr8")
AttributeError: CvBridge instance has no attribute 'imgmsg_to_cv'
In hydo I installed ros-hydro-opencv2  and ros-hydro-vision-opencv but opencv2 was not found in indigo.
I am wondering if the opencv2 package needs to be built for indigo or installed from git?

A:

This sounds like a bug in camera_calibration in Indigo; you should report it against the camera_calibration bug tracker.

Originally posted by ahendrix with karma: 47576 on 2014-05-28
This answer was ACCEPTED on the original site
Post score: 1

Original comments
Comment by amerino on 2014-05-28:
Yes it does. Already reported. I will accept your answer as soon the bug report is accepted. Thank you.
Comment by amerino on 2014-06-01:
It's a bug:  https://github.com/ros-perception/image_pipeline/issues/74

