Q:

kinect dies when using the follower example on a turtlebot

I'm trying to test out the follower example on my turtlebot.  Everything seems to work fine, I start the follower app, the kinect comes on, then as soon as the motors move the kinect shuts off.  Sometimes the robot will move a little bit before it shuts off.  Other times it seems like the kinect is still running (red IR light is on) but the robot doesn't respond at all.
Here's what I get out of the follower app.
[kinect_laser-5] restarting process
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[kinect_laser-5]: started with pid [5010]
[kinect_laser_narrow-6] restarting process
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[kinect_laser_narrow-6]: started with pid [5011]
[ERROR] [1359235309.086725130]: Cannot load nodelet /kinect_laser_narrow for one exists with that name already
[ERROR] [1359235309.247807482]: Cannot load nodelet /openni_launch for one exists with that name already
[FATAL] [1359235309.249246773]: Service call failed!
[ERROR] [1359235309.266898245]: Cannot load nodelet /openni_launch for one exists with that name already
[ERROR] [1359235309.430194156]: Cannot load nodelet /kinect_laser for one exists with that name already
[ERROR] [1359235309.544945341]: Cannot load nodelet /kinect_laser_narrow for one exists with that name already
[FATAL] [1359235309.545510496]: Service call failed!
[ERROR] [1359235309.672300503]: Cannot load nodelet /kinect_laser for one exists with that name already
[FATAL] [1359235309.673283937]: Service call failed!
[openni_launch-3] process has died [pid 4984, exit code 255, cmd /opt/ros/fuerte/stacks/nodelet_core/nodelet/bin/nodelet load openni_camera/OpenNINodelet openni_manager __name:=openni_launch __log:=/home/turtlebot/.ros/log/20535746-67f8-11e2-a10f-00242ca9ad17/openni_launch-3.log].
log file: /home/turtlebot/.ros/log/20535746-67f8-11e2-a10f-00242ca9ad17/openni_launch-3*.log
respawning...
[openni_launch-3] restarting process
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[openni_launch-3]: started with pid [5094]
[ERROR] [1359235309.905118378]: Cannot load nodelet /kinect_laser_narrow for one exists with that name already
[kinect_laser_narrow-6] process has died [pid 5011, exit code 255, cmd /opt/ros/fuerte/stacks/nodelet_core/nodelet/bin/nodelet load pointcloud_to_laserscan/CloudToScan openni_manager cloud:=/cloud_throttled scan:=/narrow_scan __name:=kinect_laser_narrow __log:=/home/turtlebot/.ros/log/20535746-67f8-11e2-a10f-00242ca9ad17/kinect_laser_narrow-6.log].
log file: /home/turtlebot/.ros/log/20535746-67f8-11e2-a10f-00242ca9ad17/kinect_laser_narrow-6*.log
respawning...
[kinect_laser_narrow-6] restarting process
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[kinect_laser_narrow-6]: started with pid [5140]
[ERROR] [1359235310.096422664]: Cannot load nodelet /openni_launch for one exists with that name already
[FATAL] [1359235310.097852105]: Service call failed!
[kinect_laser-5] process has died [pid 5010, exit code 255, cmd /opt/ros/fuerte/stacks/nodelet_core/nodelet/bin/nodelet load pointcloud_to_laserscan/CloudToScan openni_manager cloud:=/cloud_throttled __name:=kinect_laser __log:=/home/turtlebot/.ros/log/20535746-67f8-11e2-a10f-00242ca9ad17/kinect_laser-5.log].
log file: /home/turtlebot/.ros/log/20535746-67f8-11e2-a10f-00242ca9ad17/kinect_laser-5*.log
respawning...
[kinect_laser-5] restarting process
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[kinect_laser-5]: started with pid [5152]
[ERROR] [1359235310.142476838]: Cannot load nodelet /openni_launch for one exists with that name already

Originally posted by jd on ROS Answers with karma: 62 on 2013-01-26
Post score: 0

A:

Looks like it's a hardware issue.
I brought the kinect up.  Then drove the robot around using the joystick teleop.  When it's moving very slow, the kinect stayed on.  But if it went faster the kinect died.  I verified that the voltage to the kinect is fine so it must be a current issue.  I would think that the battery pack could source plenty of current unless my batteries are going bad?

Originally posted by jd with karma: 62 on 2013-01-26
This answer was ACCEPTED on the original site
Post score: 1

