Q:

ROS2 - Realsense2 subscribing to raw camera from different computer throws exceptions

I am new to ros2 and experimenting with the intel D435 camera.
I have set up the realsense D435 node, and another simple node in python that subscribes to the RGB raw data from the camera, and outputs it to my display with opencv.
When I run these two nodes on a single computer, everything works great.
However, when I run the D435 publisher node on a second computer on the same network, I get this error often:

(source.cpp:127) Exception was thrown
during user callback!

And running gdb and breaking on caught exceptions yields me this as the source of that error message

librealsense::frame_source::invoke_callback(librealsense::frame_holder)
const () from
/opt/ros/dashing/lib/librealsense2.so.2

I still get frames from the camera, but I would really like to know why the realsense lib is complaining when I'm on two separate computers.

Originally posted by johnconn on ROS Answers with karma: 553 on 2019-07-01
Post score: 0

A:

I switched to opensplice from fastRTPS and this issue stopped reproducing.
This isn't a complete answer but knowing that the issue is coupled to fastRTPS is good enough for me.

Originally posted by johnconn with karma: 553 on 2019-08-16
This answer was ACCEPTED on the original site
Post score: 1

