Q:

Problems with 2 Dynamixels MX-28 over USB2Dynamixel

Greetings from Germany,
I have a Problem: I try to run the Pi Robot face tracking System and I'm using two dynamixel MX-28 Motors for movement. I interfaced the Motors and the PC via USB2Dynamixel USB-Interface with RS-485 connection. Running the Robotis-node via launchfile gets me the following console-message:
setting /run_id to bb081e58-9218-11e2-adf3-000bab41dd30
process[rosout-1]: started with pid [5802]
started core service [/rosout]
process[dynamixel_manager-2]: started with pid [5814]
process[dynamixel_controller_spawner1-3]: started with pid [5815]
[INFO] [WallTime: 1363864577.448834] pan_tilt_port: Pinging motor IDs 0 through 25...
[INFO] [WallTime: 1363864577.951461] pan_tilt_port controller_spawner: waiting for controller_manager dxl_manager to startup in global namespace...
[ERROR] [WallTime: 1363864579.650591] Exception thrown while getting attributes for motor 1 - Invalid response received from motor 1. Wrong packet prefix ['\xbf', '\xff']
[ERROR] [WallTime: 1363864579.665361] Exception thrown while getting attributes for motor 1 - Invalid response received from motor 1. Wrong packet prefix ['\xdf', '\xff']
[INFO] [WallTime: 1363864579.833898] pan_tilt_port: Found 1 motors - 1 MX-28 [1], initialization complete.
[INFO] [WallTime: 1363864580.160889] pan_tilt_port controller_spawner: All services are up, spawning controllers...
[INFO] [WallTime: 1363864580.424991] Controller pan_controller successfully started.
[WARN] [WallTime: 1363864580.587375] The specified motor id is not connected and responding.
[WARN] [WallTime: 1363864580.592829] Available ids: [1]
[WARN] [WallTime: 1363864580.595967] Specified id: 2
[ERROR] [WallTime: 1363864580.599861] Initialization failed. Unable to start
controller tilt_controller
[dynamixel_controller_spawner1-3] process has finished cleanly

My config file looks like that:
from math import radians
port = '/dev/ttyUSB0'
servo_param = {
1: {'name': 'head_pan_joint', 
    'home_encoder': 1024,
    'max_speed': radians(200),
    'max_ang': radians(160),
    'min_ang': radians(-160)
   },
2: {'name': 'head_tilt_joint',
    'home_encoder': 0,
    'max_speed': radians(200),
    'max_ang': radians(90.),
    'min_ang': radians(-90.)
   }

}
Thanks for your Help.

Originally posted by Bison on ROS Answers with karma: 52 on 2013-03-20
Post score: 1

A:

THE SOLUTION.
First of all thanks again for all those that answered my question.
We tried a Program under Windows to check if our servos were damaged. There we found out that there is an id preinstalled by Robotis for every motor. In both cases this id had the value 1. So every time we tried to get the motors online our controller found the first motor with id = 1 and added it to the list. But then there was no servo with the id = 2 as we indicated in the config-file.
With the dynamixel-windows-program we could change the motor ids so that we got the values we needed.

Originally posted by Bison with karma: 52 on 2013-03-20
This answer was ACCEPTED on the original site
Post score: 2

Original comments
Comment by Victor_ocv2 on 2013-03-20:
Its better if you edit your question with this information

