Q:

host is not set to this machine

Hi,
I'm new to ROS, I can ping my machine but I always get this error when I run roscore. I'm not able to use simple teleop with Husky.
I already modify the hosts file on the husky and my laptop.
thibault@ubuntu:/$ roscore
... logging to /home/thibault/.ros/log/dd413c6a-2383-11e2-91e9-0026226637c2/roslaunch-ubuntu-6616.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:47097/
ros_comm version 1.8.10

SUMMARY
========

PARAMETERS
 * /rosdistro
 * /rosversion

NODES

**WARNING: ROS_MASTER_URI [http://192.168.1.2:11411] host is not set to this machine
auto-starting new master**
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[master]: started with pid [6632]
ROS_MASTER_URI=http://ubuntu:11311/

setting /run_id to dd413c6a-2383-11e2-91e9-0026226637c2
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[rosout-1]: started with pid [6645]
started core service [/rosout]
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

Originally posted by thibault on ROS Answers with karma: 1 on 2012-10-31
Post score: 0

A:

Are you talking about the AttributeError?  Like this: http://answers.ros.org/question/36600/how-to-tell-remote-machines-not-to-start-separate-roscores-when-using-roslaunch-fuerte-regression/

Originally posted by tfoote with karma: 58457 on 2012-10-31
This answer was ACCEPTED on the original site
Post score: 0

