Q:

Gazebo Won't Start

For some reason unknown to me, I cannot get Gazebo to open. I have had it working on this machine previously. I'm running ubuntu 12.04 with ROS fuerte. Any ideas?
allenh1@muri-pc7:/opt/ros/fuerte/stacks/simulator_gazebo/gazebo_worlds$ roslaunch gazebo_worlds wg_world.launch
... logging to /home/allenh1/.ros/log/48b61258-d682-11e1-8c5b-0025648c1ab0/roslaunch-muri-pc7-5276.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://129.59.89.109:33072/

SUMMARY
========

PARAMETERS
 * /rosdistro
 * /rosversion
 * /use_sim_time
 * /wg_walls

NODES
  /
    gazebo (gazebo/gazebo)
    xml2factor_wg_walls (gazebo/spawn_model)

auto-starting new master
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[master]: started with pid [5292]
ROS_MASTER_URI=http://129.59.89.109:11311

setting /run_id to 48b61258-d682-11e1-8c5b-0025648c1ab0
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[rosout-1]: started with pid [5305]
started core service [/rosout]
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[gazebo-2]: started with pid [5319]
Gazebo multi-robot simulator, version 1.0.2
Copyright (C) 2011 Nate Koenig, John Hsu, Andrew Howard, and contributors.
Released under the Apache 2 License.
http://gazebosim.org

Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[xml2factor_wg_walls-3]: started with pid [5327]
[ INFO] [1343239086.118034332]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
Msg Waiting for master
Msg Connected to gazebo master @ http://localhost:11345
Segmentation fault (core dumped)
[gazebo-2] process has died [pid 5319, exit code 139, cmd /opt/ros/fuerte/stacks/simulator_gazebo/gazebo/scripts/gazebo /opt/ros/fuerte/stacks/simulator_gazebo/gazebo_worlds/worlds/empty.world __name:=gazebo __log:=/home/allenh1/.ros/log/48b61258-d682-11e1-8c5b-0025648c1ab0/gazebo-2.log].
log file: /home/allenh1/.ros/log/48b61258-d682-11e1-8c5b-0025648c1ab0/gazebo-2*.log
loading model xml from ros parameter

Here's with the empty world:
allenh1@muri-pc7:~$ roslaunch gazebo_worlds empty_world.launch 
... logging to /home/allenh1/.ros/log/88f94a4c-d682-11e1-87a0-0025648c1ab0/roslaunch-muri-pc7-5779.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://129.59.89.109:36018/

SUMMARY
========

PARAMETERS
 * /rosdistro
 * /rosversion
 * /use_sim_time

NODES
  /
    empty_world_server (gazebo/gazebo)
    gazebo_gui (gazebo/gui)

auto-starting new master
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[master]: started with pid [5795]
ROS_MASTER_URI=http://129.59.89.109:11311

setting /run_id to 88f94a4c-d682-11e1-87a0-0025648c1ab0
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[rosout-1]: started with pid [5808]
started core service [/rosout]
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[empty_world_server-2]: started with pid [5822]
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
process[gazebo_gui-3]: started with pid [5830]
Gazebo multi-robot simulator, version 1.0.2
Copyright (C) 2011 Nate Koenig, John Hsu, Andrew Howard, and contributors.
Released under the Apache 2 License.
http://gazebosim.org

Gazebo multi-robot simulator, version 1.0.2
Copyright (C) 2011 Nate Koenig, John Hsu, Andrew Howard, and contributors.
Released under the Apache 2 License.
http://gazebosim.org

Msg Waiting for master.[ INFO] [1343239193.941097028]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
Msg Waiting for master
Msg Connected to gazebo master @ http://localhost:11345
Segmentation fault (core dumped)
[empty_world_server-2] process has died [pid 5822, exit code 139, cmd /opt/ros/fuerte/stacks/simulator_gazebo/gazebo/scripts/gazebo /opt/ros/fuerte/stacks/simulator_gazebo/gazebo_worlds/worlds/empty.world __name:=empty_world_server __log:=/home/allenh1/.ros/log/88f94a4c-d682-11e1-87a0-0025648c1ab0/empty_world_server-2.log].
log file: /home/allenh1/.ros/log/88f94a4c-d682-11e1-87a0-0025648c1ab0/empty_world_server-2*.log

Originally posted by allenh1 on ROS Answers with karma: 3055 on 2012-07-25
Post score: 0

A:

wg_world.launch uses HeightMap, which is broken in the release (should be fixed in next release 1.6.12).
For now, you can try using the meshed version?
roslaunch gazebo_worlds wg_collada_world.launch

Originally posted by hsu with karma: 5780 on 2012-07-30
This answer was ACCEPTED on the original site
Post score: 0

